// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGa-sBUreafUshUnhAQZnthb66tA0mjTo',
    appId: '1:882621884048:web:a623d5684c87f9995e5a15',
    messagingSenderId: '882621884048',
    projectId: 'ebda3a-e-commerce',
    authDomain: 'ebda3a-e-commerce.firebaseapp.com',
    storageBucket: 'ebda3a-e-commerce.firebasestorage.app',
    measurementId: 'G-1SS5GX32R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAmx9WXptI6asJ6XAUxI93ER0Ygl7vfns',
    appId: '1:882621884048:android:6d34a8939ae7ef595e5a15',
    messagingSenderId: '882621884048',
    projectId: 'ebda3a-e-commerce',
    storageBucket: 'ebda3a-e-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vtmkQqbx6B_iFfxaDfJpOMO4uqmVWAg',
    appId: '1:882621884048:ios:8ad87ae1e35d6ccd5e5a15',
    messagingSenderId: '882621884048',
    projectId: 'ebda3a-e-commerce',
    storageBucket: 'ebda3a-e-commerce.firebasestorage.app',
    iosClientId: '882621884048-ugahiamafqles0tgiu20kgfnotehv4vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebda3a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vtmkQqbx6B_iFfxaDfJpOMO4uqmVWAg',
    appId: '1:882621884048:ios:8ad87ae1e35d6ccd5e5a15',
    messagingSenderId: '882621884048',
    projectId: 'ebda3a-e-commerce',
    storageBucket: 'ebda3a-e-commerce.firebasestorage.app',
    iosClientId: '882621884048-ugahiamafqles0tgiu20kgfnotehv4vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebda3a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGa-sBUreafUshUnhAQZnthb66tA0mjTo',
    appId: '1:882621884048:web:ff984abc8f0803045e5a15',
    messagingSenderId: '882621884048',
    projectId: 'ebda3a-e-commerce',
    authDomain: 'ebda3a-e-commerce.firebaseapp.com',
    storageBucket: 'ebda3a-e-commerce.firebasestorage.app',
    measurementId: 'G-H2ZNZTNE15',
  );
}
