import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('ar'),
  ];

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
  <LocalizationsDelegate<dynamic>>[
    _AppLocalizationsDelegate(),
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) {
    final result =
    Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(result != null, 'No AppLocalizations found in context');
    return result!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Ebda3ha',
      'homepage': 'Homepage',
      'discover': 'Discover',
      'my_order': 'My Order',
      'wishlist': 'Wishlist',
      'my_profile': 'My profile',
      'chat_support': 'Chat support',
      'light': 'Light',
      'dark': 'Dark',
      'search_hint': 'What do you search for?',
      'categories': 'Categories',
      'see_all': 'See All',
      'search_results': 'Search Results',
      'no_products_found': 'No products found',
      'error_loading_products': 'Error loading products',
      'error_loading_categories': 'Error loading categories',
      'no_categories_yet': 'No categories yet',
      'settings': 'Settings',
      'cart': 'Cart',
      'forgot_password': 'Forgot Password',
      'forgot_password_description':
      'Enter your email and we will send you a link to reset your password.',
      'enter_your_email': 'Enter your email',
      'email_required': 'Email is required',
      'enter_valid_email': 'Enter a valid email',
      'send_reset_email': 'Send Reset Email',
      'reset_email_sent_success': 'Reset email sent! Check your inbox.',
      'error_generic': 'An error occurred',
      'login': 'Login',
      'login_failed': 'Login failed',
      'welcome_back_to_ebda3ha': 'Welcome Back To Ebda3ha',
      'please_sign_in_with_your_email':
      'Please sign in with your email',
      'email_label': 'E-mail',
      'password_label': 'Password',
      'enter_your_password': 'Enter your password',
      'dont_have_account_create_account':
      'Don’t have an account? Create Account',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter your full name',
      'phone': 'Phone',
      'enter_phone': 'Enter your phone',
      'confirm_password': 'Confirm Password',
      'confirm_password_hint': 'Confirm your password',
      'sign_up': 'Sign Up',
      'already_have_account_login':
      'Already have an account? Login',
      'register_success': 'Account created successfully',
      'register_failed': 'Registration failed',
      'error': 'Error',
      'not_logged_in': 'Not logged in',
      'user': 'User',
      'chat_support_coming_soon': 'Chat support coming soon',
      'your_cart': 'Your Cart',
      'cart_empty': 'Cart is empty',
      'product_price': 'Product price',
      'shipping': 'Shipping',
      'subtotal': 'Subtotal',
      'proceed_to_checkout': 'Proceed to checkout',
      'size': 'Size',
      'color': 'Color',
      'checkout': 'Checkout',
      'step_2': 'STEP 2',
      'payment': 'Payment',
      'cash': 'Cash',
      'credit_card': 'Credit Card',
      'choose_card': 'Choose your card',
      'cash_on_delivery_selected': 'Cash on delivery selected',
      'agree_terms': 'I agree to Terms and conditions',
      'agree_terms_error': 'Please agree to Terms and conditions',
      'choose_card_first': 'Please choose a card first',
      'place_order': 'Place my order',
      'loading': 'Loading...',
      'first_name': 'First name',
      'last_name': 'Last name',
      'street': 'Street',
      'shipping_method': 'Shipping method',
      'home_delivery': 'Delivery to home',
      'home_delivery_desc': '3-7 days',
      'fast_delivery': 'Fast delivery',
      'fast_delivery_desc': '2-3 days',
      'coupon_hint': 'Have a code?',
      'copy_address': 'Copy address data from shipping',
      'continue_payment': 'Continue to payment',
      'order_completed': 'Order Completed',
      'thank_you_purchase':
      'Thank you for your purchase.\nYou can view your order in My Orders section.',
      'continue_shopping': 'Continue shopping',
      'search': 'What are you looking for?',
      'no_products': 'No products found',
      'no_categories_found': 'No categories found',
      'banner_not_found': 'Banner not found',
      'error_loading_sections': 'Error loading sections',
      'section': 'Section',
      'accessories': 'Accessories',
      'up_to_50_off': 'up to 50% off',
      'clothing_upper': 'CLOTHING',
      'accessories_upper': 'ACCESSORIES',
      'shoes_upper': 'SHOES',
      'collection_upper': 'COLLECTION',
      'my_orders': 'My Orders',
      'pending': 'Pending',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'pending_upper': 'PENDING',
      'delivered_upper': 'DELIVERED',
      'cancelled_upper': 'CANCELLED',
      'order_number': 'Order',
      'tracking_number': 'Tracking number',
      'quantity': 'Quantity',
      'details': 'Details',
      'not_assigned_yet': 'Not assigned yet',
      'no_pending_orders': 'No pending orders yet',
      'no_delivered_orders': 'No delivered orders yet',
      'no_cancelled_orders': 'No cancelled orders yet',
      'no_orders': 'No orders yet',
      'your_order_delivered': 'Your order is delivered',
      'your_order_cancelled': 'Your order is cancelled',
      'your_order_on_way': 'Your order is on the way',
      'rate_product_points': 'Rate product to get 5 points for collect.',
      'this_order_cancelled': 'This order was cancelled.',
      'click_track_order': 'Click here to track your order',
      'delivery_address': 'Delivery address',
      'sub_total': 'Sub Total',
      'total': 'Total',
      'return_home': 'Return home',
      'rate': 'Rate',
      'order': 'Order',
      'rate_product': 'Rate Product',
      'already_rated': 'You already rated this order.',
      'write_review': 'Please write a short review',
      'review_success': 'Review submitted successfully',
      'review_reward': 'Submit your review to get 5 points',
      'products_to_review': 'Products to review',
      'write_something':
      'Would you like to write anything about this product?',
      'submit_review': 'Submit Review',
      'add_card': 'Add Card',
      'card_number': 'Card number',
      'card_holder': 'Card holder',
      'expiry_date': 'Expiry date',
      'cvc': 'CVC',
      'debit_card': 'Debit card',
      'submit': 'Submit',
      'field_required': 'Field required',
      'invalid_number': 'Invalid number',
      'invalid_card': 'This card number is not valid',
      'payment_details': 'Payment Details',
      'no_saved_cards': 'No saved cards yet',
      'default_card': 'Default',
      'payment_failed_message':
      'Credit card verification failed. Please check your information and try again.',
      'payment_validation': 'Payment Validation',
      'thank_you': 'Thank you!',
      'payment_done_successfully': 'Payment done successfully',
      'home': 'Home',
      'description': 'Description',
      'reviews': 'Reviews',
      'add_to_cart': 'Add to Cart',
      'adding': 'Adding...',
      'out_of_5': 'out of 5',
      'no_description': 'No description available for this product',
      'profile_photo_updated': 'Profile photo updated',
      'change_password': 'Change Password',
      'enter_new_password': 'Enter new password',
      'password_min_6': 'Password must be at least 6 characters',
      'password_updated_success': 'Password updated successfully',
      'failed_update_password': 'Failed to update password',
      'requires_recent_login':
      'For security, log in again then try changing the password.',
      'welcome': 'Welcome',
      'your_full_name': 'Your full name',
      'add_full_name': 'Add your full name',
      'your_email': 'Your E-mail',
      'your_password': 'Your password',
      'your_mobile_number': 'Your mobile number',
      'add_mobile_number': 'Add your mobile number',
      'mobile_number': 'Mobile Number',
      'your_address': 'Your Address',
      'add_address': 'Add your address',
      'add_payment_information': 'Add Your Information',
      'cancel': 'Cancel',
      'save': 'Save',
      'address': 'Address',
      'notifications': 'Notifications',
      'no_notifications_yet': 'No notifications yet',
      'language': 'Language',
      'theme': 'Theme',
      'choose_language': 'Choose Language',
      'choose_theme': 'Choose Theme',
      'light_mode': 'Light Mode',
      'dark_mode': 'Dark Mode',
      'logout': 'Log out',
      'logout_confirm': 'Are you sure you want to log out?',
      'terms_of_use': 'Terms of Use',
      'terms_content': 'These are your terms...',
      'close': 'Close',
      'wishlist_empty': 'Wishlist is empty ❤️',
      'no_results': 'No results',
      'removed_from_wishlist': 'Removed from wishlist',
      'added_to_cart': 'Added to cart',
      'arabic': 'Arabic',
      'english': 'English',
      'recommended': 'Recommended',
      'new_arrival': 'New Arrival',
      'featured_products': 'Featured Products',
      'bags_products': 'Bags Products',
      'shoes': 'Shoes',
      'bags': 'Bags',
      'clothing': 'Clothing',
      'accessories_category': 'Accessories',
      'collection': 'Collection',
      'offer_accessories_title': 'Accessories',
      'offer_accessories_subtitle': 'Up to 50% off',
      'step_1': 'STEP 1',
      'country': 'Country',
      'city': 'City',
      'coupon_code': 'Coupon Code',
      'validate': 'Validate',
      'billing_address': 'Billing Address',
      'checkout_title': 'Checkout',
      'add_new': 'Add new+',
      'or_checkout_with': 'or check out with',
      'cardholder_name': 'CARDHOLDER NAME',
      'valid_thru': 'VALID THRU',
      'card_name': 'Card name',
      'complete': 'Complete',
      'card_type_credit': 'Credit card',
      'billing_copy_address': 'Copy address',
      'support_chat_title': 'Customer Service',
      'support_chat_subtitle': 'Support Chat',
      'support_chat_subtitle_ar': 'Support Chat',
      'support_choose_language_mixed': 'Choose language / اختر اللغة',
      'support_welcome_message': 'Hello! Welcome to Customer Care Service. We will be happy to help you. Please provide more details about your issue before we can start.',
      'support_welcome_message_ar': 'Hello! Welcome to Customer Care Service. We will be happy to help you. Please provide more details about your issue before we can start.',
      'support_select_order_message': 'Please select the order related to your issue.',
      'support_select_order_message_ar': 'Please select the order related to your issue.',
      'support_checking_order': 'Thank you. Checking your order now.',
      'support_checking_order_ar': 'Thank you. Checking your order now.',
      'support_order_delayed': 'I checked your order, and it seems there is a slight delay. You should receive it within 2 days.',
      'support_order_delayed_ar': 'I checked your order, and it seems there is a slight delay. You should receive it within 2 days.',
      'support_delivered_transfer': 'Our system shows this order as delivered. I will now transfer your chat to a support agent for further help.',
      'support_delivered_transfer_ar': 'Our system shows this order as delivered. I will now transfer your chat to a support agent for further help.',
      'support_transfer_message': 'Your conversation has been transferred to a support agent.',
      'support_transfer_message_ar': 'Your conversation has been transferred to a support agent.',
      'support_other_transfer': 'You will now be transferred to a support agent for further assistance.',
      'support_other_transfer_ar': 'You will now be transferred to a support agent for further assistance.',
      'support_cancel_possible': 'This order is still being processed and can be canceled. We will start the cancellation request now.',
      'support_cancel_possible_ar': 'This order is still being processed and can be canceled. We will start the cancellation request now.',
      'support_cancel_not_possible': 'This order cannot be canceled automatically right now. I will transfer your chat to a support agent.',
      'support_cancel_not_possible_ar': 'This order cannot be canceled automatically right now. I will transfer your chat to a support agent.',
      'support_return_possible': 'This order has been delivered, and we can start the return request.',
      'support_return_possible_ar': 'This order has been delivered, and we can start the return request.',
      'support_return_not_possible': 'Returns are available only after delivery. I will transfer your chat to a support agent for further help.',
      'support_return_not_possible_ar': 'Returns are available only after delivery. I will transfer your chat to a support agent for further help.',
      'support_damaged_transfer': 'Thank you. This case needs review by a support agent. Transferring your chat now.',
      'support_damaged_transfer_ar': 'Thank you. This case needs review by a support agent. Transferring your chat now.',
      'support_write_message': 'Message',
      'support_write_message_ar': 'Message',
      'support_no_orders': 'No orders available',
      'support_no_orders_ar': 'No orders available',
      'support_issue_not_received': "I didn't receive my parcel",
      'support_issue_not_received_ar': "I didn't receive my parcel",
      'support_issue_cancel': 'I want to cancel my order',
      'support_issue_cancel_ar': 'I want to cancel my order',
      'support_issue_return': 'I want to return my order',
      'support_issue_return_ar': 'I want to return my order',
      'support_issue_damaged': 'Package was damaged',
      'support_issue_damaged_ar': 'Package was damaged',
      'support_issue_other': 'Other',
      'support_issue_other_ar': 'Other',
      'support_order_label': 'Order',
      'support_order_label_ar': 'Order',
      'support_items': 'items',
      'support_items_ar': 'items',
      'support_select': 'Select',
      'support_select_ar': 'Select',
      'customer_service_bot_name': 'Customer Service',
      'customer_service_bot_name_ar': 'Customer Service',
      'support_chat_title_ar': 'Customer Service',
      'support_choose_language_mixed_ar': 'Choose language / اختر اللغة',
      'support_main_title': 'What’s your issue?',
      'support_main_title_ar': 'What’s your issue?',
      'support_sub_issue_title': 'Choose the issue type',
      'support_sub_issue_title_ar': 'Choose the issue type',
      'support_main_order_issues': 'Order Issues',
      'support_main_order_issues_ar': 'Order Issues',
      'support_main_item_quality': 'Item Quality',
      'support_main_item_quality_ar': 'Item Quality',
      'support_main_payment_issues': 'Payment Issues',
      'support_main_payment_issues_ar': 'Payment Issues',
      'support_main_technical_assistance': 'Technical Assistance',
      'support_main_technical_assistance_ar': 'Technical Assistance',
      'support_no_matching_orders': 'No matching orders found for this issue',
      'support_no_matching_orders_ar': 'No matching orders found for this issue',
      'system': 'System'
    },
    'ar': {
      'app_name': 'إبداعها',
      'homepage': 'الرئيسية',
      'discover': 'اكتشف',
      'my_order': 'طلباتي',
      'wishlist': 'المفضلة',
      'my_profile': 'حسابي',
      'chat_support': 'الدعم',
      'light': 'فاتح',
      'dark': 'داكن',
      'search_hint': 'بتدور على إيه؟',
      'categories': 'الأقسام',
      'see_all': 'عرض الكل',
      'search_results': 'نتائج البحث',
      'no_products_found': 'لا توجد منتجات',
      'error_loading_products': 'حدث خطأ أثناء تحميل المنتجات',
      'error_loading_categories': 'حدث خطأ أثناء تحميل الأقسام',
      'no_categories_yet': 'لا توجد أقسام بعد',
      'settings': 'الإعدادات',
      'cart': 'السلة',
      'forgot_password': 'نسيت كلمة المرور',
      'forgot_password_description':
      'ادخل بريدك الإلكتروني وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
      'enter_your_email': 'ادخل بريدك الإلكتروني',
      'email_required': 'البريد الإلكتروني مطلوب',
      'enter_valid_email': 'ادخل بريدًا إلكترونيًا صحيحًا',
      'send_reset_email': 'إرسال رابط التعيين',
      'reset_email_sent_success':
      'تم إرسال رابط إعادة التعيين، راجع بريدك الإلكتروني.',
      'error_generic': 'حدث خطأ',
      'login': 'تسجيل الدخول',
      'login_failed': 'فشل تسجيل الدخول',
      'welcome_back_to_ebda3ha': 'مرحبًا بعودتك إلى إبداعها',
      'please_sign_in_with_your_email':
      'يرجى تسجيل الدخول باستخدام بريدك الإلكتروني',
      'email_label': 'البريد الإلكتروني',
      'password_label': 'كلمة المرور',
      'enter_your_password': 'ادخل كلمة المرور',
      'dont_have_account_create_account':
      'ليس لديك حساب؟ أنشئ حسابًا',
      'full_name': 'الاسم بالكامل',
      'enter_full_name': 'ادخل الاسم بالكامل',
      'phone': 'رقم الهاتف',
      'enter_phone': 'ادخل رقم الهاتف',
      'confirm_password': 'تأكيد كلمة المرور',
      'confirm_password_hint': 'أكد كلمة المرور',
      'sign_up': 'إنشاء حساب',
      'already_have_account_login':
      'لديك حساب بالفعل؟ سجل الدخول',
      'register_success': 'تم إنشاء الحساب بنجاح',
      'register_failed': 'فشل إنشاء الحساب',
      'error': 'خطأ',
      'not_logged_in': 'لم يتم تسجيل الدخول',
      'user': 'مستخدم',
      'chat_support_coming_soon': 'الدعم عبر المحادثة قريبًا',
      'your_cart': 'السلة',
      'cart_empty': 'السلة فارغة',
      'product_price': 'سعر المنتجات',
      'shipping': 'الشحن',
      'subtotal': 'المجموع',
      'proceed_to_checkout': 'المتابعة إلى الدفع',
      'size': 'المقاس',
      'color': 'اللون',
      'checkout': 'الدفع',
      'step_2': 'الخطوة ٢',
      'payment': 'الدفع',
      'cash': 'كاش',
      'credit_card': 'بطاقة',
      'choose_card': 'اختر البطاقة',
      'cash_on_delivery_selected': 'تم اختيار الدفع عند الاستلام',
      'agree_terms': 'أوافق على الشروط والأحكام',
      'agree_terms_error': 'يجب الموافقة على الشروط',
      'choose_card_first': 'اختر بطاقة أولًا',
      'place_order': 'إتمام الطلب',
      'loading': 'جاري التحميل...',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'street': 'الشارع',
      'shipping_method': 'طريقة الشحن',
      'home_delivery': 'توصيل للمنزل',
      'home_delivery_desc': 'من 3 إلى 7 أيام',
      'fast_delivery': 'شحن سريع',
      'fast_delivery_desc': 'من 2 إلى 3 أيام',
      'coupon_hint': 'هل لديك كود؟',
      'copy_address': 'نسخ العنوان',
      'continue_payment': 'متابعة الدفع',
      'order_completed': 'تم إكمال الطلب',
      'thank_you_purchase':
      'شكرًا لشرائك.\nيمكنك مشاهدة طلبك في قسم طلباتي.',
      'continue_shopping': 'متابعة التسوق',
      'search': 'بتدور على إيه؟',
      'no_products': 'لا توجد منتجات',
      'no_categories_found': 'لا توجد أقسام',
      'banner_not_found': 'البانر غير موجود',
      'error_loading_sections': 'حدث خطأ أثناء تحميل الأقسام',
      'section': 'قسم',
      'accessories': 'الإكسسوارات',
      'up_to_50_off': 'خصم يصل إلى 50%',
      'clothing_upper': 'الملابس',
      'accessories_upper': 'الإكسسوارات',
      'shoes_upper': 'الأحذية',
      'collection_upper': 'المجموعة',
      'my_orders': 'طلباتي',
      'pending': 'قيد الانتظار',
      'delivered': 'تم التوصيل',
      'cancelled': 'ملغي',
      'pending_upper': 'قيد الانتظار',
      'delivered_upper': 'تم التوصيل',
      'cancelled_upper': 'ملغي',
      'order_number': 'الطلب',
      'tracking_number': 'رقم التتبع',
      'quantity': 'الكمية',
      'details': 'التفاصيل',
      'not_assigned_yet': 'لم يتم التعيين بعد',
      'no_pending_orders': 'لا توجد طلبات قيد الانتظار',
      'no_delivered_orders': 'لا توجد طلبات تم توصيلها',
      'no_cancelled_orders': 'لا توجد طلبات ملغاة',
      'no_orders': 'لا توجد طلبات بعد',
      'your_order_delivered': 'تم توصيل طلبك',
      'your_order_cancelled': 'تم إلغاء طلبك',
      'your_order_on_way': 'طلبك في الطريق',
      'rate_product_points': 'قيّم المنتج لتحصل على 5 نقاط.',
      'this_order_cancelled': 'تم إلغاء هذا الطلب.',
      'click_track_order': 'اضغط هنا لتتبع طلبك',
      'delivery_address': 'عنوان التوصيل',
      'sub_total': 'المجموع الفرعي',
      'total': 'الإجمالي',
      'return_home': 'العودة',
      'rate': 'تقييم',
      'order': 'طلب',
      'rate_product': 'تقييم المنتج',
      'already_rated': 'لقد قمت بتقييم هذا الطلب بالفعل',
      'write_review': 'من فضلك اكتب تقييم',
      'review_success': 'تم إرسال التقييم بنجاح',
      'review_reward': 'أرسل تقييمك لتحصل على 5 نقاط',
      'products_to_review': 'المنتجات للتقييم',
      'write_something': 'هل تريد كتابة شيء عن المنتج؟',
      'submit_review': 'إرسال التقييم',
      'add_card': 'إضافة بطاقة',
      'card_number': 'رقم البطاقة',
      'card_holder': 'اسم حامل البطاقة',
      'expiry_date': 'تاريخ الانتهاء',
      'cvc': 'رمز الأمان',
      'debit_card': 'بطاقة خصم',
      'submit': 'إرسال',
      'field_required': 'هذا الحقل مطلوب',
      'invalid_number': 'رقم غير صالح',
      'invalid_card': 'رقم البطاقة غير صحيح',
      'payment_details': 'تفاصيل الدفع',
      'no_saved_cards': 'لا توجد بطاقات محفوظة بعد',
      'default_card': 'الافتراضية',
      'payment_failed_message':
      'فشل التحقق من البطاقة. يرجى التأكد من البيانات والمحاولة مرة أخرى.',
      'payment_validation': 'التحقق من الدفع',
      'thank_you': 'شكراً لك!',
      'payment_done_successfully': 'تم الدفع بنجاح',
      'home': 'الرئيسية',
      'description': 'الوصف',
      'reviews': 'التقييمات',
      'add_to_cart': 'أضف إلى السلة',
      'adding': 'جاري الإضافة...',
      'out_of_5': 'من 5',
      'no_description': 'لا يوجد وصف لهذا المنتج',
      'profile_photo_updated': 'تم تحديث صورة الملف الشخصي',
      'change_password': 'تغيير كلمة المرور',
      'enter_new_password': 'ادخل كلمة المرور الجديدة',
      'password_min_6': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'password_updated_success': 'تم تحديث كلمة المرور بنجاح',
      'failed_update_password': 'فشل تحديث كلمة المرور',
      'requires_recent_login':
      'لأسباب أمنية، قم بتسجيل الدخول مرة أخرى ثم حاول تغيير كلمة المرور.',
      'welcome': 'مرحبًا',
      'your_full_name': 'اسمك الكامل',
      'add_full_name': 'أضف اسمك الكامل',
      'your_email': 'بريدك الإلكتروني',
      'your_password': 'كلمة المرور',
      'your_mobile_number': 'رقم هاتفك',
      'add_mobile_number': 'أضف رقم هاتفك',
      'mobile_number': 'رقم الهاتف',
      'your_address': 'عنوانك',
      'add_address': 'أضف عنوانك',
      'add_payment_information': 'أضف معلوماتك',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'address': 'العنوان',
      'notifications': 'الإشعارات',
      'no_notifications_yet': 'لا توجد إشعارات بعد',
      'language': 'اللغة',
      'theme': 'الثيم',
      'choose_language': 'اختر اللغة',
      'choose_theme': 'اختر الثيم',
      'light_mode': 'الوضع الفاتح',
      'dark_mode': 'الوضع الداكن',
      'logout': 'تسجيل الخروج',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'terms_of_use': 'شروط الاستخدام',
      'terms_content': 'هذه هي شروط الاستخدام...',
      'close': 'إغلاق',
      'wishlist_empty': 'قائمة المفضلة فارغة ❤️',
      'no_results': 'لا توجد نتائج',
      'removed_from_wishlist': 'تمت الإزالة من المفضلة',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'arabic': 'العربية',
      'english': 'English',
      'recommended': 'الموصى به',
      'new_arrival': 'وصل حديثًا',
      'featured_products': 'منتجات مميزة',
      'bags_products': 'منتجات الشنط',
      'shoes': 'الأحذية',
      'bags': 'الشنط',
      'clothing': 'الملابس',
      'accessories_category': 'الإكسسوارات',
      'collection': 'المجموعة',
      'offer_accessories_title': 'الإكسسوارات',
      'offer_accessories_subtitle': 'خصم يصل إلى 50%',
      'step_1': 'الخطوة ١',
      'country': 'الدولة',
      'city': 'المدينة',
      'coupon_code': 'كود الخصم',
      'validate': 'تفعيل',
      'billing_address': 'عنوان الفاتورة',
      'checkout_title': 'إتمام الطلب',
      'add_new': '+إضافة جديد',
      'or_checkout_with': 'أو ادفع باستخدام',
      'cardholder_name': 'اسم صاحب البطاقة',
      'valid_thru': 'صالح حتى',
      'card_name': 'اسم البطاقة',
      'complete': 'إتمام',
      'card_type_credit': 'بطاقة ائتمان',
      'billing_copy_address': 'نسخ العنوان',
      'support_chat_title': 'خدمة العملاء',
      'support_chat_subtitle': 'الدعم الفني',
      'support_chat_subtitle_ar': 'الدعم الفني',
      'support_choose_language_mixed': 'اختر اللغة / Choose language',
      'support_welcome_message': 'مرحبًا! أهلًا بك في خدمة العملاء. يسعدنا مساعدتك. من فضلك اختر نوع المشكلة قبل أن نبدأ.',
      'support_welcome_message_ar': 'مرحبًا! أهلًا بك في خدمة العملاء. يسعدنا مساعدتك. من فضلك اختر نوع المشكلة قبل أن نبدأ.',
      'support_select_order_message': 'من فضلك اختر الطلب المرتبط بالمشكلة.',
      'support_select_order_message_ar': 'من فضلك اختر الطلب المرتبط بالمشكلة.',
      'support_checking_order': 'شكرًا لك. جارٍ فحص الطلب الآن.',
      'support_checking_order_ar': 'شكرًا لك. جارٍ فحص الطلب الآن.',
      'support_order_delayed': 'تحققنا من الطلب، ويبدو أن هناك تأخيرًا بسيطًا. من المتوقع أن يصلك خلال يومين.',
      'support_order_delayed_ar': 'تحققنا من الطلب، ويبدو أن هناك تأخيرًا بسيطًا. من المتوقع أن يصلك خلال يومين.',
      'support_delivered_transfer': 'الحالة عندنا تظهر أن الطلب تم توصيله. سنحوّل المحادثة الآن إلى أحد موظفي خدمة العملاء لمساعدتك بشكل أفضل.',
      'support_delivered_transfer_ar': 'الحالة عندنا تظهر أن الطلب تم توصيله. سنحوّل المحادثة الآن إلى أحد موظفي خدمة العملاء لمساعدتك بشكل أفضل.',
      'support_transfer_message': 'تم تحويل المحادثة إلى أحد موظفي خدمة العملاء.',
      'support_transfer_message_ar': 'تم تحويل المحادثة إلى أحد موظفي خدمة العملاء.',
      'support_other_transfer': 'سيتم تحويلك الآن إلى أحد موظفي خدمة العملاء لمساعدتك.',
      'support_other_transfer_ar': 'سيتم تحويلك الآن إلى أحد موظفي خدمة العملاء لمساعدتك.',
      'support_cancel_possible': 'هذا الطلب ما زال قيد التجهيز ويمكن إلغاءه. سنبدأ طلب الإلغاء الآن.',
      'support_cancel_possible_ar': 'هذا الطلب ما زال قيد التجهيز ويمكن إلغاءه. سنبدأ طلب الإلغاء الآن.',
      'support_cancel_not_possible': 'لا يمكن إلغاء هذا الطلب الآن من خلال البوت. سنحوّل المحادثة إلى موظف خدمة العملاء.',
      'support_cancel_not_possible_ar': 'لا يمكن إلغاء هذا الطلب الآن من خلال البوت. سنحوّل المحادثة إلى موظف خدمة العملاء.',
      'support_return_possible': 'هذا الطلب تم توصيله، ويمكننا البدء في طلب الإرجاع.',
      'support_return_possible_ar': 'هذا الطلب تم توصيله، ويمكننا البدء في طلب الإرجاع.',
      'support_return_not_possible': 'الإرجاع متاح فقط بعد توصيل الطلب. سنحوّل المحادثة إلى موظف خدمة العملاء للمساعدة.',
      'support_return_not_possible_ar': 'الإرجاع متاح فقط بعد توصيل الطلب. سنحوّل المحادثة إلى موظف خدمة العملاء للمساعدة.',
      'support_damaged_transfer': 'شكرًا لك. هذه الحالة تحتاج مراجعة من أحد موظفي خدمة العملاء. سنحوّل المحادثة الآن.',
      'support_damaged_transfer_ar': 'شكرًا لك. هذه الحالة تحتاج مراجعة من أحد موظفي خدمة العملاء. سنحوّل المحادثة الآن.',
      'support_write_message': 'اكتب رسالة',
      'support_write_message_ar': 'اكتب رسالة',
      'support_no_orders': 'لا توجد طلبات متاحة',
      'support_no_orders_ar': 'لا توجد طلبات متاحة',
      'support_issue_not_received': 'لم أستلم طلبي',
      'support_issue_not_received_ar': 'لم أستلم طلبي',
      'support_issue_cancel': 'أريد إلغاء الطلب',
      'support_issue_cancel_ar': 'أريد إلغاء الطلب',
      'support_issue_return': 'أريد إرجاع الطلب',
      'support_issue_return_ar': 'أريد إرجاع الطلب',
      'support_issue_damaged': 'الطلب تالف',
      'support_issue_damaged_ar': 'الطلب تالف',
      'support_issue_other': 'أخرى',
      'support_issue_other_ar': 'أخرى',
      'support_order_label': 'الطلب',
      'support_order_label_ar': 'الطلب',
      'support_items': 'منتج',
      'support_items_ar': 'منتج',
      'support_select': 'اختيار',
      'support_select_ar': 'اختيار',
      'customer_service_bot_name': 'خدمة العملاء',
      'customer_service_bot_name_ar': 'خدمة العملاء',
      'support_chat_title_ar': 'خدمة العملاء',
      'support_choose_language_mixed_ar': 'اختر اللغة / Choose language',
      'support_main_title': 'ما هي مشكلتك؟',
      'support_main_title_ar': 'ما هي مشكلتك؟',
      'support_sub_issue_title': 'اختر نوع المشكلة',
      'support_sub_issue_title_ar': 'اختر نوع المشكلة',
      'support_main_order_issues': 'مشاكل الطلبات',
      'support_main_order_issues_ar': 'مشاكل الطلبات',
      'support_main_item_quality': 'جودة المنتج',
      'support_main_item_quality_ar': 'جودة المنتج',
      'support_main_payment_issues': 'مشاكل الدفع',
      'support_main_payment_issues_ar': 'مشاكل الدفع',
      'support_main_technical_assistance': 'الدعم الفني',
      'support_main_technical_assistance_ar': 'الدعم الفني',
      'support_no_matching_orders': 'لا توجد طلبات مناسبة لهذه المشكلة',
      'support_no_matching_orders_ar': 'لا توجد طلبات مناسبة لهذه المشكلة',
      'system': 'تلقائي'
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension LocalizationExtension on BuildContext {
  AppLocalizations get tr => AppLocalizations.of(this);

  bool get isArabic => Localizations.localeOf(this).languageCode == 'ar';

  bool get isDarkMode => Theme.of(this).brightness == Brightness.dark;
}